/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wxmylife_jni_JNIUtils */

#ifndef _Included_com_xxm_sublibrary_jni_Ja
#define _Included_com_xxm_sublibrary_jni_Ja
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wxmylife_jni_JNIUtils
 * Method:    getPublicKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_w_c_s_jni_Ja_getPublicKey
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
